version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: daily
      time: "16:30"
    commit-message:
      prefix: "composer"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "16:30"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
